### ISSUE TITLE
Feature Request: support some streamlit configuration (at least Theming)

### ISSUE THREAD

**Issue by Abdelgha-4** [whitphx/stlite#997]
Hello,

Streamlit apps may have a [config.toml](https://docs.streamlit.io/develop/api-reference/configuration/config.toml) that offers many options for customization and finer control over the app. I think that supporting at least some of the options would be a convenient and useful feature.

For example this is the configuration I was using on a Streamlit app, but when moving to stlite I found no way to apply the same config.
```toml
[theme]
primaryColor ="#E51E2B"
secondaryBackgroundColor = "#F5F5F5"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
magicEnabled = false
fastReruns = true
enforceSerializableSessionState = true
```
